import { escapeHTML as e, type Page } from './model.ts';

export function courseBody(page: Page, pages: Page[], base: string): string {
  const social = page.section === '社会';
  const link = (path: string, title: string, cls = '') => `<a${cls ? ` class="${cls}"` : ''} href="${base}${encodeURI(path)}">${e(title)}</a>`;
  const lessons = pages.filter(p => p.lesson && p.section === page.section);
  const groups = [...new Set(lessons.map(p => p.group))];
  const start = social ? 'social-studies/textbook/F01.html' : '000005/reading/00_start_here/learning_plan.html';
  const intro = social ? '世界の暮らし、歴史の流れ、社会の仕組み。「どうして？」をつなげながら、中学校3年間の社会を学びます。' : '観察して、予想して、確かめる。身近なふしぎから、小学校・中学校の理科をつなげます。';
  const extra = social ? `<section class="section-block"><div class="section-heading"><div><p class="eyebrow">CONNECT THE DOTS</p><h2>流れとつながりを、確かめよう。</h2></div></div><div class="course-resources">${link('social-studies/atlas.html', '地図・統計資料を読む')}${link('social-studies/timeline.html', '歴史の年表を見る')}${link('social-studies/glossary.html', '用語を確かめる')}${link('social-studies/workbook.html', '単元の確認問題を解く')}${link('social-studies/coverage.html', '学習範囲を確認する')}${link('social-studies/SOURCES.html', '出典と参考資料を見る')}</div><h3 class="practice-heading">総合問題に挑戦する</h3><p>まずは問題だけに取り組んでから、解答を開いて振り返りましょう。</p><div class="mock-grid">${[1, 2, 3].map(n => `<article><p class="eyebrow">PRACTICE 0${n}</p><h4>総合問題 ${n}</h4><div class="button-row">${link(`social-studies/mock-0${n}.html`, '問題を開く →', 'button')}${link(`social-studies/mock-0${n}-answers.html`, '解答・解説')}</div></article>`).join('')}</div></section>` : `<section class="section-block"><div class="section-heading"><div><p class="eyebrow">BUILD YOUR FOUNDATION</p><h2>最初の150枚から、少しずつ。</h2></div></div><p>一度に全部を覚える必要はありません。基礎のカードで知識を確かめ、読み物や実験・計算のページへ戻ってみましょう。</p><div class="course-resources">${link('000005/reading/00_start_here/core_first_150.html', '基礎150枚の読み方')}${link('000005/reading/01_skills/calculation_strategy.html', '計算問題の考え方')}${link('000005/reading/01_skills/experiment_reasoning.html', '実験から考える')}${link('000005/reading/01_skills/misconceptions.html', 'よくある思い違い')}${link('000005/anki/IMPORT_GUIDE.html', 'Ankiの取り込み案内')}${link('000005/sources/SOURCES.html', '出典と参考資料')}</div></section>`;
  return `<main id="main" class="wrap section-block course-home"><header class="landing-header"><p class="eyebrow">${social ? 'SOCIAL STUDIES' : 'SCIENCE'} / LEARNING ROOM</p><h1>${page.section}の学習室。</h1><p>${intro}</p><div class="button-row">${link(start, 'はじめの一歩へ →', 'button primary')}${link(`review.html?set=${social ? 'social' : 'science'}`, 'カードで復習する', 'button')}${link('downloads.html', '教材を保存する')}</div></header><section class="course-guide"><div><p class="eyebrow">GET STARTED</p><h2>${social ? '入口 → 地理 → 歴史 → 公民' : '学び方 → 基礎 → 気になる分野'}</h2><p>${social ? '社会が初めてなら入口F01から。基礎を押さえたら、地理・歴史・公民へ。学習案内では取り組む順序と復習の考え方を説明しています。' : 'はじめに学習計画を読み、知っていること・これから知りたいことを整理します。学年別マップや物理・化学・生物・地学からも選べます。'}</p>${link(social ? 'social-studies/study-guide.html' : '000005/reading/00_start_here/how_to_read_cards.html', '学び方を読む →')}</div><div><p class="eyebrow">SMALL STEPS COUNT</p><h2>読んだら、確かめる。</h2><p>答えを見る前に、自分のことばで説明してみましょう。「読み終えた」「あとで読む」のボタンで、進み具合をこのブラウザーに残せます。</p>${link('library.html', '読了・あとで読むを確認 →')}</div></section>${extra}<section><div class="section-heading"><div><p class="eyebrow">CHOOSE A CHAPTER</p><h2>単元を選ぶ。</h2></div><span class="tiny">${lessons.length}の読み物</span></div>${groups.map(group => `<details class="course-chapters"${group === groups[0] ? ' open' : ''}><summary>${e(group)}<span>${lessons.filter(p => p.group === group).length}件</span></summary><div class="lesson-list">${lessons.filter(p => p.group === group).map(p => `<div><a class="lesson-link" href="${base}${encodeURI(p.path)}" data-record-path="${e(p.path)}"><span>${e(p.title)}</span><span class="read-marker" aria-label="読了" hidden>読了</span></a><small>約${p.minutes}分</small></div>`).join('')}</div></details>`).join('')}</section><details class="course-notes"><summary>教材パッケージの詳しい案内</summary><div class="prose">${page.body}</div></details><p class="source-link"><a href="https://github.com/lkjsxc/a/blob/main/${encodeURI(page.source)}">この教材の原稿を見る</a> · ${link('about.html', '使い方と教材の位置づけ')}</p></main>`;
}
